#!/bin/bash
set -euo pipefail

. "$HOME"/repo/.venv/bin/activate

QUERY=$(cat <<EOF
select
  p.page_namespace,
  p.page_title
from
  linktarget lt
  left join categorylinks cl on lt.lt_id = cl.cl_target_id
  left join page p on cl.cl_from = p.page_id
  left join file on p.page_title = file.file_name
  left join filerevision fr on fr.fr_id = file.file_latest
  left join filetypes ft on file.file_type = ft.ft_id
where
  lt.lt_namespace = 14
  and lt.lt_title = 'All_non-free_media'
  and p.page_namespace = 6
  and fr_width * fr_height / 1000000 > 0.105
  and ft_major_mime = 'image'
  and not exists (
    select
      1
    from
      templatelinks tl
      left join linktarget lt on tl.tl_target_id = lt.lt_id
    where
      p.page_id = tl.tl_from
      and tl.tl_from_namespace = 6
      and lt.lt_namespace = 10
      and lt.lt_title in (
        'Non-free_no_reduce',
        'Non-free_reduce',
        'Non-free_manual_reduce'
      )
  )
EOF
)

nfcbot reduce-tagger --always -log:reduce-tagger.log -mysqlquery:"$QUERY"
